### ISSUE TITLE
Sequence diagram overlap when print

### ISSUE THREAD

**Issue by zainul** [inkdropapp/inkdrop-export-print#1]
i try to using sequence diagram but the printed page is overlap
it's expected or not ?

![Image link](https://prnt.sc/lwfsab "")

**Comment by craftzdog** [comment]
I can't see the image

**Comment by craftzdog** [comment]
Next version will fix this problem. Thanks!

**Comment by craftzdog** [comment]
Inkdrop v3.4.0 is out.
Please update the app and update plugins by `ipm update`.
